name: Generate terraform docs

on:
  - pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Render terraform docs and push changes back to PR
        uses: terraform-docs/gh-actions@main
        with:
          working-dir: .
          recursive: true
          recursive-path: modules
          output-file: README.md
          output-method: replace
          git-push: true
